server:
  port: 8020
spring:
  application:
    name: consumer #当前服务注册在eureka server名称
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/ #注册中心访问地址
    instance:
      prefer-ip-address: true  #是否将当前服务的ip注册到eureka server
