server:
    port: 8762
spring:
    application:
        name: nativeconfigser
    profiles:
        active: native              #表示配置文件获取方式，native表示从本地拿
    cloud:
        config:
            server:
                native:
                    search-locations: classpath:/shared      #本地配置文件存放路径
