server:
  port: 8888
spring:
  application:
    name: configserver
  cloud:
    config:
      label: master
      server:
        git:
          uri: https://github.com/wstdd/myspringcloud.git
          searchPaths: config
          username: wstdd123@163.com
          password: wstdd@123
          force-pull: true
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/